apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-world-demo
  title: Hello World Node.js App
  description: A simple template for kind cluster testing
spec:
  owner: guest
  type: service

  # 1. This defines the input form in the Backstage UI
  parameters:
    - title: PR Details
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: The URL of the repo (e.g., github.com?owner=my-org&repo=my-app)
        title:
          title: PR Title
          type: string
          default: "Internal: Add maintenance documentation"
        branchName:
          title: New Branch Name
          type: string
          default: "docs/maintenance-guide"
        name:
          title: What is your name?
          type: string

  # 2. These are the steps the backend executes
  steps:
    - id: fetch-base
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton  # Points to the local folder
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.title }}

    - id: create-pr
      name: Open Pull Request
      action: publish:github:pull-request
      input:
        # The target repository
        repoUrl: ${{ parameters.repoUrl }}
        branchName: ${{ parameters.branchName }}
        title: ${{ parameters.title }}
        description: "This PR was automatically generated by Backstage."
        # If the branch exists, update it rather than failing
        update: true
        # Commit message
        commitMessage: "docs: add maintenance manual"
